### PR TITLE
Contract v1.2.0

### PR DESCRIPTION
**Pull request by germartinez**
Use Gnosis Safe contract v1.2.0

### CODE REVIEW

**Comment by hexyls** [comment]
It would be cool to make createProxyAndExecTransaction payable to match the change to execTransaction in Gnosis Safe v1.2.0.

**Comment by germartinez** [comment]
Hello @hexyls,
That is a planned feature that will be included in the vew version of the CPKFactory contract
You can track the progress here: https://github.com/gnosis/contract-proxy-kit/pull/106

**Comment by cag** [comment]
Just a note about the merge conflict: in the `xdai` branch that got merged, the file `migrations/1-deploy-contracts.js` got removed from the index, since it is a compilation output of `migrations-ts/1-deploy-contracts.ts`. Since this branch is currently a merge target of #130, we should wait for that PR to resolve before considering this one.

**Review by cag — APPROVED** [review]
LGTM

**Pull request merged**
